Das Debian-Paketmanagement-Buch -- Blick hinter die Kulissen eines freien Buches
================================================================================
:author:    Axel Beckert <abe@debian.org>, Frank Hofmann <frank.hofmann@efho.de>
:backend:   slidy
:data-uri:  http://www.dpmb.org/
:max-width: 94%
:icons:

Wir haben da so ein Buch angefangen ...
---------------------------------------

* Titel: Debian-Paketmanagement
* Autoren: Axel Beckert und Frank Hofmann
* Entstehung: seit Frühjahr 2013
* Umfang: etwa 500 Seiten
* ist vollständig in lesbarem Deutsch verfaßt
** Zielgruppe: fortgeschrittene Einsteiger, Profis
** auch eine englische Übersetzung ist in Vorbereitung

Inhalt des Buches
-----------------

* beschreibt detailliert den Umgang mit der Paketverwaltung auf
  deb-basierten Systemen via dpkg, APT und Aptitude
* fokussiert auf Debian GNU/Linux, passt aber auch für Ubuntu, LinuxMint, etc.
* Teil 1: Konzepte -- Ideen hinter der Paketverwaltung
* Teil 2: Werkzeuge -- die Programme und deren Möglichkeiten
* Teil 3: Praxis -- Lösungen für komplexere Alltagssituationen

Status
~~~~~~

* Teil 1 und 2: soweit komplett
* Teil 3: hat noch größere Lücken

Veröffentlichungen
------------------

* Inhalt steht unter einer freien Lizenz --
  http://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0]
* https://github.com/dpmb/dpmb[Quellcode auf GitHub] verfügbar: https://github.com/dpmb/dpmb
* Aus dem Quellcode kann jeder selbst folgende Formate bauen:
** HTML (mehrere Varianten)
** E-Book (bisher PDF, EPUB und MobiPocket)
** Debian-Paket mit PDF, HTML und EPUB.
* Fertig gebaute E-Books zum Online-Lesen und direkten Download unter http://book.dpmb.org/
** Bisher mittels https://www.gitbook.com/book/dpmb/dpmb/details[Gitbook], Rendering dort hat aber Unschönheiten
** Seit kurzem selbstgehostet https://github.com/xtaran/CGI-Github-Webhook[mittels Eigenbau (Perl-Modul CGI::Github::Webhook)]
* Gedrucktes Buch (kostenpflichtig) geplant, Veröffentlichung bei
  http://www.onyxneon.com/[Onyx Neon]

Wie entsteht das Buch
---------------------

* Basis: 
** Schreiben ist ein kreativer Prozess und bedingt daher eine
   entsprechende Stimmung -- geht nicht "auf Knopfdruck"
** Orientierung des Schreibprozesses am Entwicklungsweg von Software
** Auswahl der verwendeten (Software)Werkzeuge gemäß unseren Bedürfnissen

* Schreiben an einem festen Ort: hauptsächlich in Zürich und Berlin
** jeder werkelt weitestgehend unabhängig für sich
** Austausch via Telefon, Mail und Videokonferenz
** von Zeit zu Zeit ein explizites Zusammentreffen für das Buch
   (sogenannte "Buch-Sprints")

* Schreiben von unterwegs aus
** Zusammentreffen im Rahmen von Linux-Events
** im Wohnmobil (Axel) und im Zug (Frank)
** auch etwas abgelegene Orte, um die entsprechende Ruhe zu haben und
   von nichts anderem abgelenkt zu werden

Quellen des Buches
------------------

* Hosting über die Plattform GitHub
** kostenfrei für freie (öffentlich verfügbare) Software
** sehr populär und vielen Entwicklern/Lesern vertraut
** erlaubt die unkomplizierte Koordination von Fremdbeiträgen
** rendert Quelldateien in AsciiDoc rudimentär zur Ansicht im Repo

* Ablauf in drei Schritten:
** lokale Kopie vom Buch-Repo ziehen: `git clone git://github.com/dpmb/dpmb.git`
** Buch lokal bauen, bspw. via `make pdf`, `make html` oder `dpkg-buildpackage`
** lesen, kommentieren und verbessern

Versionierung
-------------

* Versionskontrollsystem (VCS): Git
** freies, stabiles und sehr flexibles VCS
** Kombination aus zentralem Archiv und dezentralen Kopien
** dezentrales, verteiltes Arbeiten ohne permanente Abhängigkeit des Internets
** regelmäßiges Zusammenführen ("Synchronisieren") der Inhalte

* erlaubt ... 
** ... das zeitweise Arbeiten ohne Internet
** ... das Nachvollziehen, wer was wann worin geändert hat
** ... das Rückgängigmachen von Änderungen

Mitmachen und Feedback
----------------------

* Mit GitHub-Konto: Per Pull-Request auf GitHub
.. Auf https://github.com/dpmb/dpmb oben rechts auf den "Fork"-Knopf
   klicken.
.. Änderungen machen und in das damit erstellte eigene GitHub-Repo
   des Buches einchecken:
*** Entweder das eigene GitHub-Repo lokal auschecken ("Repo klonen"),
    lokal Änderungen vornehmen, committen und wieder ins eigene
    GitHub-Repo pushen.
*** Oder einfach auf der Webseite Deines geforkten GitHub-Repos die
    Änderungen direkt via Browser vornehmen.
.. Webseite des eigenen Repos aufrufen (oder neu laden) und auf "Pull
   Request" klicken.
* Ohne GitHub-Konto: Patches per E-Mail einsenden
.. Lokale Kopie des Buch-Repos erzeugen: `git clone git://github.com/dpmb/dpmb.git`
.. Änderungen durchführen und in der lokalen Instanz einchecken.
.. Patch in Datei exportieren `git format-patch origin/master` und Datei an
   mailto:buch@dpmb.org[buch@dpmb.org] schicken.

* Wir schauen uns den Patch bzw. den Pull-Request an
** Entweder akzeptieren wir die Änderungen oder lehnen sie ab
** Falls akzeptiert, "mergen" wir den Pull-Request oder wenden den
   Patch mit `git am` an.

* Synchronisation der lokalen Kopien (`git pull`), damit alle
  Mitwirkenden wieder auf dem aktuellen Stand sind

Software
--------

* lokal
** Git als VCS
** Asciidoc als plattformunabhängige Auszeichnungssprache des
   Buchinhalts
*** `asciidoc` oder `asciidoctor` als primärer Parser
*** `a2x`, `dblatex` und `pdflatex` zum Erzeugen der PDFs
** Make zur Anstossen der Übersetzung in die Ausgabeformate
** Node.js und https://www.npmjs.com/package/gitbook[Gitbook
   (installiert via npm)] zum Debuggen, falls das Buch auf Gitbook
   nicht mehr baut.

* im Web
** GitHub zur Verwaltung, für Statistik, zur Koordination und für
   Benachrichtigungen
** https://travis-ci.org/dpmb/dpmb/builds[Travis-CI zum automatisches
   Testen, ob das Buch nach einem Commit noch baut], auch bei
   Pull-Requests.
** Gitbook zum automatischen Bauen der Online-Version und E-Books nach
   jedem `git push`.

Baustellen
----------

* Woran wir derzeit noch arbeiten:
** Feinschliff Teil 2 -- konsistente Wortwahl, Stichworte
** Vervollständigung von Teil 3 -- Inhalt
** Markup ans Rendering bei Gitbook anpassen.

* Wo wir noch Unterstützung brauchen:
** Praxisteil (Teil 3) -- Wir können nicht alle Szenarien nachbauen.
** Welche Probleme sind mit deb-Paketen und den Werkzeugen aufgetaucht,
   und wie wurde das Problem gelöst?


Von uns nicht genutzte Alternativen zur Veröffentlichung
--------------------------------------------------------

* https://leanpub.com/[Leanpub] (primär E-Books, auch kostenlose
  Bücher oder Zahl-was-Du-willst-Schema möglich)
* https://www.publi.de/[Epubli] (Print-on-Demand, aber auch
  Vorab-Druck auf Vorschuß des Autors; Buchpreisbindung in Dtl., gibt
  aber auch https://www.epubli.co.uk/[epubli.co.uk])
* http://www.lulu.com/[Lulu] (primär Print-on-Demand)
* http://www.bookbaby.com/[BookBaby] (E-Books und gedruckte Bücher)

Markdown im Vergleich zu AsciiDoc
---------------------------------

* Einfacher, aber auch weniger mächtig als Asciidoc
* Standard-Format für Bücher bei Leanpub und Gitbook

Varianten
~~~~~~~~~

* http://markua.com/[Markua] (zukünftiger Markdown-Dialekt speziell für Bücher von Leanpub)
* https://leanpub.com/help/manual[Leanpub Flavoured Markdown] (LFM; auf Bücher angepasster Markdown-Dialekt)
* https://help.github.com/articles/github-flavored-markdown/[GitHub Flavoured Markdown]
  (GFM; wird auch http://help.gitbook.com/format/markdown.html[von Gitbook verwendet])

Danke und Kontakt
-----------------

Danke fürs Interesse und Zuhören.

Feedback bitte an
~~~~~~~~~~~~~~~~~

* Per E-Mail an mailto:buch@dpmb.org[buch@dpmb.org]
* https://github.com/dpmb/dpmb/pulls[Via Pull Request auf GitHub]
* Axel oder Frank direkt

Links
~~~~~

* Webseite: http://www.dpmb.org/
* Lesen: http://book.dpmb.org/
* Quellcode: https://github.com/dpmb/dpmb
* Folien: https://github.com/dpmb/talks/blob/master/hinter-den-kulissen.adoc
